# Generated by Django 4.1.5 on 2023-02-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_passwordless_simplejwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Support'), (2, 'Customer'), (3, 'Admin')], null=True),
        ),
    ]
